### ISSUE TITLE
Invalid file depth？

### ISSUE THREAD

**Issue by frank-pian** [mattflow/cbmp#2]

**Comment by mattflow** [comment]
can you give an example to reproduce?

**Comment by nitko12** [comment]
Hi, I've encountered this issue too.

https://github.com/mattflow/cbmp/blob/e5e90306da6a47c90f5b0766af820014535dd080/cbmp.c#L178

this function has a bug, if you give it bytes < 4, it will malloc it and try to cast to integer (4 bytes usually) and by doing that it reads data out of allocated memory, usually there will be zero, but when using -O2 or -O3 I've got weird results.

I'll make a PR with the fix.

**Comment by mattflow** [comment]
Awesome thanks. I'll take a look and merge

**Comment by mattflow** [comment]
Addressed in #3
